# Generated by Django 3.2.12 on 2024-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, null=True, verbose_name='apellido')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('telefono', models.IntegerField(null=True, verbose_name='telefono')),
            ],
        ),
    ]
